### ISSUE TITLE
Document the U-SPS deployment via Terraform

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#111]

**Comment by LucaCinquini** [comment]
Perhaps this is the proper location:
https://unity-sds.gitbook.io/docs/developer-docs/science-processing/docs/admin-guide?
We can always move the page I guess.

**Comment by drewm-jpl** [comment]
@LucaCinquini I've added the docs to GitBook. I created a page named "Cluster Provisioning with Terraform" and placed it in  the Developers guide. This location appears to be where the other service areas are placing their build docs.

The link is here:
https://unity-sds.gitbook.io/docs/developer-docs/science-processing/docs/developers-guide/cluster-provisioning-with-terraform

**Comment by riverma** [comment]
Hey @drewm-jpl - excellent write-up! Is a developer actually expected to deploy a cluster? If not - I'd suggest moving setup guides to the Admin section of the Science Processing GitBook area. Dev docs are especially good for those who want to understand the code or make modifications to it.

**Comment by drewm-jpl** [comment]
Thanks for the feedback @riverma, I've moved it to the Admin Section.
