### ISSUE TITLE
As a project manager, i want to set default compute types for processing nodes at deploy time, so that i can predict costs for the system (Static)

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-sps-prototype#142]

**Comment by LucaCinquini** [comment]
This epic was actually implemented by U-CS. The EC2 type for Verdi workers is specified as one of the parameters when creating the ELS cluster, part of the metadata. For example:

{"clustername":"luca-eks-dev","owner":"luca","projectname":"unity","nodegroups":{"group1":{"instancetype":"m5.xlarge","nodecount":"1"}}}

**Comment by LucaCinquini** [comment]
Thanks Drew - can you point me to the location in the Terraform file?

**Comment by drewm-jpl** [comment]
Here it is: https://github.com/unity-sds/unity-sps-prototype/blob/171-scale-worker-nodes/terraform-unity/variables.tf#L148-L168
