### ISSUE TITLE
[New Feature]: Create a Terraform script to copy ancillary data

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#149]
**Checked for duplicates**
No duplicates exist.

**Alternatives considered**
The ancillary data could be copied via a shell command but this Terraform script would make the task easier.

**Describe the feature request**
Create a Terraform script that would copy data from an S3 bucket to an existing EFS partition, or that can run an arbitrary shell script. The script would be executed as a post-deployment step by a project.

**Comment by mike-gangl** [comment]
@LucaCinquini i'm wondering how this scales. Making this a part of the terraform script only works if the deployment of the SPS is configurable by the project directly. In a world where we are creating a venue separate from the deployment of a workflow, how does this work? 

Straw man: the algorithm package can have "dependencies" that are copied at the time of deployment (e.g. the WPS-T deploy process) so that subsequent executions would have this available. @hookhua is there anything in the WPS-T spec that would allow for that? or the Application Package spec?

**Comment by hookhua** [comment]
It seems like there are a few different topics here.

(a) There are some built-in support for deployment at run-time in the OGC specs, but it is at the context of the algorithm steps. OGC WPS-T supports deployment of algorithms into an WPS-T endpoint (the ADES). And the Application Package has notions of data staging, but that is in the context of accessing and copying data into a local processing step / job.

(b) There is a separate topic of setting up a local "cache" of static ancillary/auxiliary files into a venue environment, which is reused across several jobs. This is more so for granules that are expected to have recurrent data access patterns.

(c) Separately still is the notion of setting up the venue resources, such as deploying an ADES cluster inside U-SPS for a tenant.

So overall, we can see the following steps:
1. U-SPS deploys a tenant-specific resource (e.g. ADES processing cluster) into a venue.
2. Pre-stage static ancillary/auxiliary files into S3 that is collocated with the ADES. 
3. Deploy algorithm(s) into one of the ADES clusters.
4. Submits jobs to the ADES cluster.
5. When the job gets dispatched to run, it will do the stage-in, process, and stage-out steps local to each compute node. This may be referencing any local "cache" of the static files collocated to the compute.

If this ticket is referring to (2), then Terraform script could be used for this setup of a collocated set of data. This is useful for setting up a complete environment with resources and data. There could then be a similar Terraform script for the tear-down stage when a tenant is done.

Alternatively, if this ticket is referring to (5), then it can leverage the built-in data staging logic by U-DS. This prevents Terraform scripts from having to duplicate similar capabilities as the stage-in step. e.g. the logic of staging data from a DAAC via the TEA using EDL credentials. For some ADESes, the backend could be EFS as well, so the same could be done for stage-in into a shared EFS volume.

**Comment by LucaCinquini** [comment]
Hi guys, this ticket refers to step 2. above. Using a Terraform or shell script to stage the ancillary data (once only) was only meant to be a temporary solution, to show how a project could do it. I agree that building a general functionality into the system following an OGS spec would be a much better idea, if we can do it - but also a much longer effort.

**Comment by LucaCinquini** [comment]
Closing this ticket as "non-fix" for now... Copying ancillary data is for now a manual step executed by the project, from some S3 location to some EFS partition provisioned off band. The ticket can be re-opened when the use case is better defined.
