### ISSUE TITLE
[New Feature]: Pass environment variables to a Docker container execution

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#157]
**Checked for duplicates**
No duplicates exist.

**Alternatives considered**
The alternative is to hard-code the env values within each Docker image, which results in different images used on different venues. Not a viable option in the long term.

**Describe the feature request**
Venue-specific parameters (such as the DAPA client id, the U-DS S3 bucket, the DAPA API URL) are currently hard-wired in the Dockerfile used to create the Docker image that executes a generic algorithm (see https://github.com/unity-sds/unity-sps-register_job/blob/main/docker/Dockerfile). What we need instead is the ability to pass these env variables (which exists in each Verdi container) to the Docker command "docker run...." which is executed by HySDS.

**Comment by LucaCinquini** [comment]
As discussed with Gerald, this is a general capability that needs to be added to the core HySDS libraries. It will involve adding a new section to the JSON job spec file, and parsing that section before the job RunConfig file is created.

**Comment by NamrataM** [comment]
Making the core HySDS change is not possible at this moment. It will need updates across multiple HySDS core repos and the HySDS UIs. Just updating the HySDS job worker's docker command construction to include the environment variables will break core.

Another way to make this happen is store the `-e ENVIRONMENT_VAR=VALUE` in the job spec document of HySDS which is created on a process deployment. The only concern is, in the scenario any environment variable is updated, if the SPS cluster is not redeployed, then HySDS will have stale information. We would need to re-deploy the process that were registered before that point.

For now, we will not be pursuing the update to Docker container execution as it has a lot of repercussions in HySDS core.
