### ISSUE TITLE
[New Feature]: Pass arbitrary labels when requesting a job execution

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#160]
**Checked for duplicates**
No duplicates exist.

**Alternatives considered**
No alternatives exist.

**Describe the feature request**
We want to be able to pass arbitrary information to a job execution request, in particular labels, so that that information can be used to filter jobs when querying and monitoring. Many Epics to be implemented this FY can leverage this functionality.

**Comment by LucaCinquini** [comment]
Examples of information to be passed:
o Identity of operator who submitted the job
o Arbitrary labels

Perhaps we could add an optional key/value map as an input parameter to each deployed algorithm. An example of this input map could be:
o identify=xyz
o priority=high
o scenario=A

Questions:
o Should this information should be stored in the WPS-T front-end SQL database?
o Should it also be passed down to HySDS? Can HySDS support it?
o Must investigate whether the WPS-T API already supports querying with additional filters, if not should Unity extend the API?

**Comment by LucaCinquini** [comment]
A first implementation of labels support was completed by Ryan.
Next suggested steps:
o Deploy an instance of this U-SPS onto MCP-Test and make it available to the UI team to test
o Populate that database with 100 jobs with some different labels
o Write documentation on GitBook on how to pass the information as part of a job request

**Comment by ryanhunter-jpl** [comment]
Documentation on job labels: https://unity-sds.gitbook.io/docs/developer-docs/science-processing/docs/developers-guide/job-labels
