### ISSUE TITLE
[New Feature]: New SPS API with stub pre-warm method

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#163]
**Checked for duplicates**
No duplicates exists - this is a new features.

**Alternatives considered**
No alternatives exist.

**Describe the feature request**
Create a Docker container to host the new SPS API that will be used to manage the back-end ADES implementations. 
Include a single stub method called pre_warm(int num_nodes) that -for now- does not interact with the back-end, instead alwas returns true.
Deploy as part of the U-SPS cluster.

**Comment by LucaCinquini** [comment]
Ryan to start work. He also suggested using serverless as implementation, which could be a good option although it would tie us to AWS only (not multi-cloud).

**Comment by LucaCinquini** [comment]
Ryan completed the stub implementation using FastAPI (not a big fan). Next steps to conclude the task:
o Create SPS-API documentation in GitBook
o Create tests in u-sps-protptype, issue PR for Drew

**Comment by ryanhunter-jpl** [comment]
Docs for current API version: https://app.gitbook.com/o/xZRqGQeQXJ0RP4VMj7Lq/s/UMIRhLdbRQTvMWop8Il9/developer-docs/science-processing/docs/users-guide/unity-sps-api
