### ISSUE TITLE
[Bug]: The WPS-T method to register a process may time out while building the PGE Docker image

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#167]
**Checked for duplicates**

> Have you checked for duplicate issue tickets?
No duplicates exist.

**Describe the bug**

> A clear and concise description of what the bug is. Plain-text snippets preferred but screenshots welcome.

The WPS-T method to register a process may time out while building the PGE Docker image. This causes the first WPS-T request to fail, and also has implications about corresponding tests failing.

> Proposed solutions

1) The WPS-T register method could be changed to be an asynchronous invocation, with an additional status method that checks the result of the registration. This might involve extending the WPS-T API.

2) Or, we could try to speed up the process of building the Docker image for the HySDS base PGE, which is governed by the files in this directory: Identify where the Docker container is built: https://github.com/unity-sds/unity-sps-register_job/tree/main/docker 
Most of the functionality in the Docker file could be moved to a new Docker file base image: "hysds/pge-base:develop” ghcr.io/unity-sds/unity-sps-prototype/pge-base:unity-v0.0.1" which is build as part of the other HySDS Docker images in "https://github.com/unity-sds/unity-sps-prototype/tree/main/hysds/pge". Then the Docker image for the specific PGE is built from the latter. Note that we still need to change the code in the 2 MCP-DEV/TEST repositories for now.

**Comment by ryanhunter-jpl** [comment]
> Also, it might help to pre-load the Docker image "hysds/pge-base" (and possibly the new parent image) as part of the TF deployment of the wps-t container, if possible.

Yes, definitely. Just did a quick test and the docker base image pull takes about 2 minutes on my machine (about a 1g download.) The other image dependencies take about 30s to install, so I'm going to try:
1. build different base image that includes the sps-specific pge dependencies
2. pre-load that image as a part of the deployment

**Comment by ryanhunter-jpl** [comment]
Doing the above reduced the call time to about 50s. I suspect the majority of that is the image upload time, but I'm not sure we can really get around that without an asynchronous call.

**Comment by LucaCinquini** [comment]
That might be enough, thanks. We could independently run the build process and time the different parts, but later.

**Comment by LucaCinquini** [comment]
Drew pointed out that the parent image was not really downloaded at deployment time. After fixing that bug, the creating of the Docker container only takes a few seconds. Closing.
