### ISSUE TITLE
[Dependency]: Add SPS API URL to the SSM store

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#222]
Requested by On-Demand team

**Comment by ryanhunter-jpl** [comment]
This is already implemented in the SPS terraform [here](https://github.com/unity-sds/unity-sps-prototype/blob/7d33d78ee65157b606449e9d76e6633d4f7bd476/terraform-modules/terraform-unity-sps-hysds-cluster/sps_api.tf#L22). Each SPS deployments create the following SSM params:
`/unity/sps/{sps-deployment-name}/spsApi/hostname`
`/unity/sps/{sps-deployment-name}/spsApi/port`

Example:
`/unity/sps/unity-dev-sps-hysds-eks-ryan/spsApi/hostname`

I can change it to be in one URL ssm param if that's preferred, I'm not totally sure why I chose to separate in to `hostname` and `port`.

**Comment by LucaCinquini** [comment]
I think having a single parameter ("endpoint"? "url"?) would be preferable, thanks.

**Comment by ryanhunter-jpl** [comment]
Change made and merged here: https://github.com/unity-sds/unity-sps-prototype/pull/229
