### ISSUE TITLE
[Bug]: Deploying duplicate processes locks database

### ISSUE THREAD

**Issue by ryanhunter-jpl** [unity-sds/unity-sps-prototype#236]
**Checked for duplicates**

> Have you checked for duplicate issue tickets?

Yes - I've already checked

**Describe the bug**
When deploying a process with the same id:processVersion combintation, the WPS-T endpoint returns a 500 and subsequent requests to the server fail with a "database locked error"

**What did you expect?**
The server should respond with an appropriate status code and message without failing. Subsequent requests to the server should not fail.

**Reproducible steps**

1. Deploy process `chirp:develop` to WPS-T
2. Send another request to deploy `chirp:develop` to WPS-T
3. Observe error, optionally send other requests that modify the database such as a DELETE PROCESS request to see database locked

**What is your environment?**
Deployments in Dev in Test environment

**Comment by LucaCinquini** [comment]
The expected behavior is to return an error if the process already exists. The client will need to first unregister the process and then register the new version again.

**Comment by LucaCinquini** [comment]
Drew implemented and tested.
