### ISSUE TITLE
[New Feature]: Create a CWL Operator or simply a CWL DAG to execute a CWL workflow

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#259]
Acceptance Criteria:
o Demonstrated execution of a simple CWL workflow onto the SPS+Airflow system
o CI/CD pipeline for nightly execution of a simple CWL workflow (""Hello World"")

**Comment by LucaCinquini** [comment]
The first attempt to solve this problem involved creating a Kubernetes pod that included a CWL container as the main container, and the Docker-In-Docker container as a "Sidecar" container - see example pod: 
https://github.com/unity-sds/unity-sps-prototype/blob/cwl-docker/cwl/cwl_job.yaml

Note that the "Sidecar" container is available as optional in Kubernetes 1.28 and enabled by default in Kubernetes 1.29, so testing on the laptop involved installing minikube which supports the latest Kubernetes version.

It turns out that this 2-containers Kubernetes Job works just fine when executed in the latest minikube, but if it is run through Airflow with a KubernetesPodOperator, the Sidecar "dind" container is never stopped, and therefore the DAG instance never completes.

**Comment by LucaCinquini** [comment]
The second attempt is proving more successful. This involves creating a Docker image that contains both Docker and the CWL libraries. Upon execution, the container will first start Docker, than execute the CWL workflow, then stop Docker.
This Docker container can be run as a Kubernetes Pod which is triggered by the KubernetesPodOperator. The corresponding DAG runs to completion within Airflow on a personal laptop.

**Comment by GodwinShen** [comment]
@LucaCinquini any updates on this ticket?  It's been a couple of weeks since you've posted here so I would appreciate any update that you may have.

**Comment by LucaCinquini** [comment]
Building on the last comment from before, we now have a KubernetesPodOperator that can execute any CWL workflow, with any input arguments, including invoking steps that involve running a Docker container. We are waiting on Drew to merge his Airflow changes into main first, then we can add this KPO and close the ticket.

**Comment by GodwinShen** [comment]
@LucaCinquini any updates on this ticket?

**Comment by LucaCinquini** [comment]
The CWL Operator with Docker works just fine when SPS is deployed on the Kubernetes cluster on the laptop. I am trying to see if it works the same when SPS with Airflow is deployed on MCP.

**Comment by LucaCinquini** [comment]
It turns out that the Docker images built on the mac (with the new chip) don't seem to work on AWS. Had to switch the build to use the Github Actions on GitHub. After a few other fixes, now we have a working DAG that is able to execute a CWL workflow that includes a Docker container. What is still not working is to use the proper AWS permissions, but that is another matter. Closing.
