### ISSUE TITLE
[New Feature]: Deploy SPS w/ Airflow onto sbg venue

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#262]
Acceptance Criteria:
o Ability to log onto Airflow UI and execute simple jobs

Dependencies:
From CS: all shared services installed on sbg venue
From DS: all data services installed and configured on sbg venue

**Comment by GodwinShen** [comment]
@LucaCinquini looks like this probably isn't getting done in this sprint right?  Perhaps we should move it off at least one sprint to 24.1.4?

**Comment by LucaCinquini** [comment]
Correct, I don't think the SBG venue is setup yet.

**Comment by LucaCinquini** [comment]
From Drew on Slack:
I’ve created nightly SPS deployments in both unity-venue-dev and unity-sbg-dev. For both of these deployments, I’ve enabled [a nightly smoke test through Github Actions](https://github.com/unity-sds/unity-sps/actions/runs/8196578109/job/22417094255) which pings the Airflow health endpoint and evaluates the status of each of the major Airflow components. I’ll continue to build out our nightly test suite with the goal being to eventually include functional tests involving workflows.
