### ISSUE TITLE
[New Feature]: Deployment of latest SPS w/Airflow onto sbg venue

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#270]
Acceptance Criteria:
o Demonstrated invocation of all currently available SBG CWL workflows on sbg venue
o Up to date CI/CD pipelines for automatic execution of all SBG workflows

**Comment by drewm-jpl** [comment]
@LucaCinquini I've deployed into `unity-sbg-dev` can this be marked as done?

**Comment by LucaCinquini** [comment]
Thanks Drew, yes!
