### ISSUE TITLE
[Task]: Reconfigure SDS Automated Tests

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#273]
Reconfigure the SPS automated tests to use the SPS nightly clusters in mcp-venue-dev and mcp-venue-test

**Comment by drewm-jpl** [comment]
This is also complete, we have nightly smoke tests that test SPS deployments in `unity-venue-dev`, `unity-venue-test`, and `unity-sbg-dev`

https://github.com/unity-sds/unity-sps/actions/workflows/smoke_tests.yml
