### ISSUE TITLE
[New feature] Add Terraform parameters to customize the amount of disk available to each Pod

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#279]
Update the TF deployment to allow the user to specify the amount of EBS disk attached to each node. Make the default something like 100GB. Also allow each Pod to request a configurable fraction, like 10-50 GB.

**Comment by drewm-jpl** [comment]
This work is complete.

Related PRs which have been merged:
https://github.com/unity-sds/unity-sps/pull/17
https://github.com/unity-sds/unity-cs-infra/pull/71
