### ISSUE TITLE
Develop Jupyter Notebook as "makeshift" U-SPS orchestrator

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#31]
The notebook needs to be able to deploy, submit and monitor an algorithm

### Acceptance Criteria

- deployment of Algorithm for L1A and L1B SounderSIPS proess algorithms to the SPS
- Example queries to u-ds for finding data to process (L1A and L1B)
- submitting the found data in a WPS request for processing
- monitoring processing
- ability to access generated data product after process is complete

https://docs.google.com/spreadsheets/d/1xH5Sfjl7DvOdLtZnOceWryp9x4Of2i9z8lU8Mdfpsms/edit#gid=0

**Comment by rtapella** [comment]
#65

**Comment by LucaCinquini** [comment]
Anil and Rob implemented the first version of the JN successfully. Updated version will be developed in time.
