### ISSUE TITLE
Interface with Unity-Data-Services

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#61]
Use U-DS to download input data and upload output data. This is closed in favor of splitting this into #63 and #64

**Comment by mike-gangl** [comment]
@LucaCinquini i think we should split the 'download data from U-DS' functionality from the 'ingest data the SPS processed' in terms of Epics. It would be better scoped.testable if we do that, but let me know what you think.

**Comment by LucaCinquini** [comment]
Sure that's fine - I will take care of that.

**Comment by LucaCinquini** [comment]
Closing this epic since it is replaced by the 2 separate Epics for data download/upload.
