### ISSUE TITLE
Define Jupyter U-SPS orchestrator

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-sps-prototype#65]
Features and release roadmap
https://docs.google.com/spreadsheets/d/1xH5Sfjl7DvOdLtZnOceWryp9x4Of2i9z8lU8Mdfpsms/edit#gid=0

**Comment by LucaCinquini** [comment]
Thanks for that. I concur with all the steps for V1 - beyond that, I think we need to do more research.
Also, I think the step where you download the output data ("Put data somewhere convenient for further analysis (download, mounted in Jupyter, etc.)" should also be part of v1.

**Comment by rtapella** [comment]
Moved that one to v1
