### ISSUE TITLE
Create Docker image for HySDS Factotum

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-prototype#7]
`factotum` can be split into 2 parts:
- background processing `celery` tasks (user rules processing, orchestrator, etc.)
- the actual job execution, running the `docker run <image>:<tag> <command>` command

the tricky part is connecting the K8 pod to the docker client/server
may need to do further research on how to run factotum completely in kubernetes w/o having to run a dedicated instance

**Comment by DustinKLo** [comment]
this may help: https://estl.tech/accessing-docker-from-a-kubernetes-pod-68996709c04b

**Comment by LucaCinquini** [comment]
This post shows the difference between DockerInsideDocker (DinD) as in the first post above and DockerOutsideOfDocker (DOOD), which basically means running a separate Docker engine inside each Pod:
https://applatix.com/case-docker-docker-kubernetes-part-2/

**Comment by LucaCinquini** [comment]
This is also a similar post: https://medium.com/hootsuite-engineering/building-docker-images-inside-kubernetes-42c6af855f25 with same conclusion that DIND is better than DOOD.

**Comment by DustinKLo** [comment]
task partially completed here: #36
will look into this ticket later when deploying to AWS/cloud
